from units import Position

EMULATION_MODE = True

ZERO_X = 0
ZERO_Y = 135
ZERO_Z = 95.5
ZERO_POSITION = Position(ZERO_X, ZERO_Y, ZERO_Z)
CROUCHED_POSITION = Position(ZERO_X, ZERO_Y - 10, ZERO_Z)
BELLY_DOWN_POSITION = Position(ZERO_X, 10, 190)
CARRY_POSITION = Position(40, 10, 190)

SERVO_COMMAND_DELAY = 0.05

LEFT = -1
RIGHT = 1

FRONT = 1
REAR = -1

HIP_UP_ANGLE_DEG = -90
SERVO_OFFSET_DEG = 180

LEG_GEOMETRY_A_MM = 53.863
LEG_GEOMETRY_THETA_DEG = 100.27
HIP_SEPERATION_MM = 85
SERVO_DISTANCE_MM = 46
THIGH_LENGTH_MM = 30
CALF_LENGTH_MM = 120

CONTROLLER_BUTTON_COUNT = 22